"""Keyword rules for the ranking engine.

Keywords are stored as plain strings. The scorer lowercases English text
before matching, so English keywords here should be lowercase. Arabic
keywords are matched as-is (case does not apply).
"""

# ── Positive keywords (English) ────────────────────────────────────────
# Each entry is a substring that should appear in the combined text.
POSITIVE_EN: list[str] = [
    # Python
    "python",
    "data",
    "django",
    "flask",
    "fastapi",
    # SQL & databases (English)
    "sql",
    "mysql",
    "postgresql",
    "postgres",
    "sqlite",
    "sql server",
    "mssql",
    "database",
    "databases",
    "db design",
    "database design",
    "database development",
    "database administration",
    "database optimization",
    "database migration",
    "database normalization",
    "normalization",
    "erd",
    "entity relationship",
    "schema design",
    "data modeling",
    "datamodel",
    "stored procedures",
    "stored procedure",
    "views",
    "indexes",
    "index optimization",
    "query optimization",
    # ETL / Data Engineering
    "etl",
    "elt",
    "data engineering",
    "pipeline",
    "data pipeline",
    "data pipelines",
    "airflow",
    "apache airflow",
    # Scraping / Automation
    "web scraping",
    "webscraping",
    "scraping",
    "scraper",
    "automation",
    "automate",
    # CSV / Excel
    "csv",
    "excel",
    "excel import",
    "excel export",
    "data cleaning",
    "data cleansing",
    "cleansing",
    "data processing",
    "data migration",
    # API + Data
    "api to database",
    "importing data",
    "exporting data",
    "data import",
    "data export",
    # Performance / Maintenance
    "database performance",
    "database troubleshooting",
    "report generation",
    "sql report",
    # General data work
    "database",
    "mariadb",
    "mongodb",
    "mongo",
    "redis",
    "elasticsearch",
    "data warehouse",
    "warehouse",
    "data lake",
    "bigquery",
    "redshift",
    "snowflake",
]

# ── Positive keywords (Arabic) ─────────────────────────────────────────
POSITIVE_AR: list[str] = [
    "قاعدة بيانات",
    "قاعدة البيانات",
    "قواعد البيانات",
    "تصميم قاعدة بيانات",
    "إنشاء قاعدة بيانات",
    "بناء قاعدة بيانات",
    "تطوير قاعدة بيانات",
    "تحسين قاعدة البيانات",
    "تهيئة قاعدة البيانات",
    "ضبط قاعدة البيانات",
    "مخطط قاعدة البيانات",
    "استعلامات",
    "ماي إس كيو إل",
    "ماي سيكوال",
    "بوستجريس",
    "بوستجرس",
    "استيراد بيانات",
    "استيراد البيانات",
    "تصدير بيانات",
    "تصدير البيانات",
    "تنظيف البيانات",
    "تنظيف بيانات",
    "معالجة بيانات",
    "معالجة البيانات",
    "استخراج البيانات",
    "استخراج بيانات",
    "تحويل البيانات",
    "تحويل بيانات",
    "تحميل البيانات",
    "تحميل بيانات",
    "جمع البيانات",
    "جمع بيانات",
    "تحليل هيكل قاعدة البيانات",
    "ماشين",
    "داتابيز",
    "داتا",
    "داتا بيز",
    "معلومات",
    "اس كيو ال",
    "سيكوال",
    "سيكوال سيرفر",
    "ميكروسوفت سيكوال سيرفر",
    "سكربت",
    "أتمتة",
    "أوتوميشن",
    "سكربت بايثون",
    "بايثون",
]

# ── Negative keywords (English) ────────────────────────────────────────
NEGATIVE_EN: list[str] = [
    # Web frameworks (when primary focus, not incidental)
    "laravel",
    "Full-Stack Developer",
    "wordpress",
    "shopify",
    "woocommerce",
    "wix",
    "squarespace",
    # Frontend / UI
    "frontend",
    "front-end",
    "ui design",
    "ux design",
    "ui/ux",
    # Mobile
    "flutter",
    "swift ios",
    "android app",
    "mobile app",
    # JS frameworks (when sole focus)
    "react ",
    "angular",
    "vue.js",
    "vuejs",
    "next.js",
    "nextjs",
    "nuxt",
    # Design / Creative
    "graphic design",
    "logo design",
    "logo",
    "motion graphics",
    "video editing",
    "video production",
    "adobe photoshop",
    "illustrator",
    "figma",
    # Marketing / SEO
    "seo",
    "social media",
    "facebook ads",
    "google ads",
    "marketing",
    "content writing",
    "copywriting",
    "blog writing",
    # Other non-data
    "translation",
    "translating",
    "accounting",
    "bookkeeping",
    "customer support",
    "virtual assistant",
]

# ── Negative keywords (Arabic) ─────────────────────────────────────────
NEGATIVE_AR: list[str] = [
    "موقع إلكتروني كامل",
    "موقع كامل",
    "مطور ويب",
    "ادخال",
    "متجر إلكتروني",
    "تطبيق جوال",
    "رياكت",
    "واجهة مستخدم",
    "تصميم واجهات",
    "وردبريس",
    "لارافيل",
    "ريأكت",
    "أنجولار",
    "فيو",
    "تصميم شعار",
    "مونتاج",
    "فيديو",
    "تسويق",
    "سوشيال ميديا",
    "كتابة محتوى",
    "ترجمة",
    "دعم فني",
    "مساعدة عملاء",
]

# ── Threshold ───────────────────────────────────────────────────────────
# Projects scoring at or above this value are accepted.
ACCEPT_THRESHOLD: int = 55

# ── Point values ────────────────────────────────────────────────────────
POSITIVE_POINTS: int = 12
NEGATIVE_POINTS: int = 15
